// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmQIp_XKsNPmTykTX9rcOMcmsW10Gptdw',
    appId: '1:590248236308:web:ac57ea0073715a8a4f5e01',
    messagingSenderId: '590248236308',
    projectId: 'heart-crystal',
    authDomain: 'heart-crystal.firebaseapp.com',
    storageBucket: 'heart-crystal.firebasestorage.app',
    measurementId: 'G-43RLL7SM0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOBXeeKA_LrzwqKHEk6lAwoJSFsV8vXlc',
    appId: '1:590248236308:android:ad338b0a7a1371ca4f5e01',
    messagingSenderId: '590248236308',
    projectId: 'heart-crystal',
    storageBucket: 'heart-crystal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC89akmfrhQx8gIpqMNx33rSq-MxPFWPCU',
    appId: '1:590248236308:ios:854a717ba187032b4f5e01',
    messagingSenderId: '590248236308',
    projectId: 'heart-crystal',
    storageBucket: 'heart-crystal.firebasestorage.app',
    iosClientId: '590248236308-3fsbjoqohnn8st87q30cdiaf290ghiv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC89akmfrhQx8gIpqMNx33rSq-MxPFWPCU',
    appId: '1:590248236308:ios:854a717ba187032b4f5e01',
    messagingSenderId: '590248236308',
    projectId: 'heart-crystal',
    storageBucket: 'heart-crystal.firebasestorage.app',
    iosClientId: '590248236308-3fsbjoqohnn8st87q30cdiaf290ghiv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmQIp_XKsNPmTykTX9rcOMcmsW10Gptdw',
    appId: '1:590248236308:web:a42d3f1ef1ef76234f5e01',
    messagingSenderId: '590248236308',
    projectId: 'heart-crystal',
    authDomain: 'heart-crystal.firebaseapp.com',
    storageBucket: 'heart-crystal.firebasestorage.app',
    measurementId: 'G-0YF682JF3P',
  );

}